# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 18:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lon', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.FloatField(default=0.0)),
                ('height', models.FloatField(default=0.0)),
                ('length', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location_type', models.CharField(choices=[('customer', 'CUSTOMER'), ('warehouse', 'WAREHOUSE')], max_length=10)),
                ('coord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_api.Coord')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('weight', models.FloatField(default=0.0)),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_api.Dimension')),
            ],
        ),
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=1.0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_api.Product')),
            ],
        ),
        migrations.CreateModel(
            name='TimeWindow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin', models.TimeField(blank=True, null=True)),
                ('end', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('factor', models.FloatField(default=1.0)),
                ('uom_type', models.CharField(choices=[('bigger', 'Bigger'), ('reference', 'Reference'), ('smaller', 'Smaller')], max_length=10)),
                ('rounding', models.IntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name='UnitOfMeasureCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='unitofmeasure',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_api.UnitOfMeasureCategory'),
        ),
        migrations.AddField(
            model_name='productitem',
            name='uom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_api.UnitOfMeasure'),
        ),
        migrations.AddField(
            model_name='product',
            name='uom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_api.UnitOfMeasure'),
        ),
        migrations.AddField(
            model_name='location',
            name='items',
            field=models.ManyToManyField(blank=True, to='data_api.ProductItem'),
        ),
        migrations.AddField(
            model_name='location',
            name='time_windows',
            field=models.ManyToManyField(blank=True, to='data_api.TimeWindow'),
        ),
        migrations.AddField(
            model_name='dimension',
            name='uom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_api.UnitOfMeasure'),
        ),
    ]
