# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 19:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_occupied', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CarrierClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier_type', models.CharField(max_length=50)),
                ('weight_cap', models.FloatField(default=0.0)),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_api.Dimension')),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_api.UnitOfMeasure')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_api.Customer')),
                ('delivery_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_api.Location')),
                ('delivery_time_windows', models.ManyToManyField(to='data_api.TimeWindow')),
                ('items', models.ManyToManyField(blank=True, to='data_api.ProductItem')),
            ],
        ),
        migrations.AddField(
            model_name='carrier',
            name='carrier_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_api.CarrierClass'),
        ),
        migrations.AddField(
            model_name='carrier',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_api.Location'),
        ),
    ]
