# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 09:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0002_auto_20161129_0257'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=1.0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_api.Product')),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_api.UnitOfMeasure')),
            ],
        ),
        migrations.RenameModel(
            old_name='ProductItem',
            new_name='InventoryItem',
        ),
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(blank=True, to='data_api.OrderItem'),
        ),
    ]
