# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 06:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0007_auto_20161206_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='uom_weight',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_weight_uom', to='data_api.UnitOfMeasure'),
        ),
        migrations.AlterField(
            model_name='product',
            name='uom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_uom', to='data_api.UnitOfMeasure'),
        ),
    ]
