# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-15 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0008_auto_20161208_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrier',
            name='fixed_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='carrier',
            name='fuel_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='carrier',
            name='service_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('normal', 'NORMAL'), ('express', 'EXPRESS')], default='normal', max_length=10),
        ),
    ]
