# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-30 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0009_auto_20170115_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='locations',
            field=models.ManyToManyField(blank=True, to='data_api.Location'),
        ),
    ]
