# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-31 05:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0010_customer_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
