# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-31 05:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0012_auto_20170131_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='destination_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trip_destination_location', to='data_api.Location'),
        ),
        migrations.AddField(
            model_name='trip',
            name='source_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trip_source_location', to='data_api.Location'),
        ),
    ]
