# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-01 17:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0013_auto_20170131_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='location_items', to='data_api.InventoryItem'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_orders', to='data_api.Location'),
        ),
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='item_orders', to='data_api.OrderItem'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='orders',
            field=models.ManyToManyField(related_name='trip_orders', to='data_api.Order'),
        ),
    ]
