# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-14 08:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0016_auto_20170212_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='is_saved',
        ),
    ]
