# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-15 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0018_auto_20170215_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_time_windows',
            field=models.ManyToManyField(blank=True, to='data_api.TimeWindow'),
        ),
    ]
