# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-15 20:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('data_api', '0020_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupSettting',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.Group')),
                ('max_carrier', models.IntegerField(default=0)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(auto_now_add=True)),
            ],
            bases=('auth.group',),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('trip_manager', 'TripManager'), ('sale_person', 'SalePerson'), ('back_office', 'BackOfficer'), ('order_manager', 'OrderManager'), ('service_admin', 'ServiceAdmin')], max_length=20),
        ),
    ]
