# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-15 20:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0021_auto_20170216_0324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupsettting',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='groupsettting',
            name='start_date',
        ),
        migrations.AddField(
            model_name='groupsettting',
            name='start_valid_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='groupsettting',
            name='valid_until',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
