# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-17 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0023_auto_20170216_0432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='orders',
            field=models.ManyToManyField(blank=True, related_name='trip_orders', to='data_api.Order'),
        ),
    ]
