# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-22 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0024_auto_20170217_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='destination_location',
        ),
        migrations.AddField(
            model_name='trip',
            name='carrier_class',
            field=models.ManyToManyField(blank=True, related_name='trip_carrier_class', to='data_api.CarrierClass'),
        ),
        migrations.AddField(
            model_name='trip',
            name='round_trip',
            field=models.BooleanField(default=True),
        ),
    ]
