# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-22 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0025_auto_20170222_1205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='carrier_class',
            new_name='carrier_classes',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='round_trip',
        ),
        migrations.AddField(
            model_name='trip',
            name='is_round_trip',
            field=models.BooleanField(default=True),
        ),
    ]
