# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-22 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0026_auto_20170222_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='carrier_classes',
            field=models.ManyToManyField(blank=True, related_name='trip_carrier_classes', to='data_api.CarrierClass'),
        ),
    ]
