# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-03 10:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0027_auto_20170222_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='source_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_source_location', to='data_api.Location'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'NEW'), ('loaded', 'LOADED'), ('delivered', 'DELIVERED')], default='new', max_length=10),
        ),
    ]
