# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-06 20:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0028_auto_20170303_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='source_location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order_source_location', to='data_api.Location'),
        ),
    ]
