# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-02 05:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0029_auto_20170307_0310'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='plan_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
