# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-02 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0030_trip_plan_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='plan_type',
            field=models.CharField(choices=[('cost', 'COST'), ('dist', 'DIST'), ('time', 'TIME')], default='cost', max_length=10),
        ),
    ]
