# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-02 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0031_trip_plan_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='plan_type',
            field=models.CharField(choices=[('cost_rank', 'COST'), ('dist_rank', 'DISTANCE'), ('time_rank', 'TIME')], default='cost', max_length=10),
        ),
    ]
