# Generated by Django 3.2.8 on 2021-10-21 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data_api', '0034_auto_20170718_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrier',
            name='carrier_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data_api.carrierclass'),
        ),
        migrations.AlterField(
            model_name='carrier',
            name='created_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carrier_created_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='carrier',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='carrier',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data_api.location'),
        ),
        migrations.AlterField(
            model_name='carrier',
            name='updated_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carrier_updated_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='carrierclass',
            name='created_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carrier_class_created_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='carrierclass',
            name='dimension',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data_api.dimension'),
        ),
        migrations.AlterField(
            model_name='carrierclass',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='carrierclass',
            name='uom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data_api.unitofmeasure'),
        ),
        migrations.AlterField(
            model_name='carrierclass',
            name='updated_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carrier_class_updated_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='coord',
            name='created_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coord_created_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coord',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='coord',
            name='updated_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coord_updated_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_created_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='updated_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_updated_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dimension',
            name='created_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dimension_created_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dimension',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dimension',
            name='uom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data_api.unitofmeasure'),
        ),
        migrations.AlterField(
            model_name='dimension',
            name='updated_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dimension_updated_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='created_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_item_created_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data_api.product'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='uom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data_api.unitofmeasure'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='updated_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_item_updated_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='location',
            name='coord',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data_api.coord'),
        ),
        migrations.AlterField(
            model_name='location',
            name='created_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_created_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='location',
            name='updated_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_updated_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='map',
            name='created_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='map_created_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='map',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='map',
            name='updated_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='map_updated_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mapoutway',
            name='created_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='map_out_way_created_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mapoutway',
            name='distance_uom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='data_api.unitofmeasure'),
        ),
        migrations.AlterField(
            model_name='mapoutway',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mapoutway',
            name='output_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='to', to='data_api.location'),
        ),
        migrations.AlterField(
            model_name='mapoutway',
            name='updated_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='map_out_way_updated_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mapway',
            name='created_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='map_way_created_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mapway',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mapway',
            name='source_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source', to='data_api.location'),
        ),
        migrations.AlterField(
            model_name='mapway',
            name='updated_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='map_way_updated_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_created_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_api.customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_orders', to='data_api.location'),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='source_location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='order_source_location', to='data_api.location'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_updated_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='created_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_item_created_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data_api.product'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='uom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data_api.unitofmeasure'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='updated_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_item_updated_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_created_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='dimension',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data_api.dimension'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='uom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='product_uom', to='data_api.unitofmeasure'),
        ),
        migrations.AlterField(
            model_name='product',
            name='uom_weight',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='product_weight_uom', to='data_api.unitofmeasure'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_updated_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='timewindow',
            name='created_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_window_created_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='timewindow',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='timewindow',
            name='updated_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_window_updated_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trip',
            name='created_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_created_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trip',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='source_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_source_location', to='data_api.location'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='updated_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_updated_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='unitofmeasure',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='unitofmeasurecategory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_api.company'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
