# Generated by Django 3.2.8 on 2021-11-03 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0037_deliveryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_images',
            field=models.ManyToManyField(related_name='order_delivery_images', to='data_api.DeliveryImage'),
        ),
    ]
