# Generated by Django 3.2.8 on 2021-11-03 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0038_order_delivery_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='end_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='end_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='receiver',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='sign_on_glass',
            field=models.ImageField(blank=True, null=True, upload_to='sign_on_glass_images/'),
        ),
        migrations.AddField(
            model_name='order',
            name='start_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='start_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='mile_in',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='trip',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_images',
            field=models.ManyToManyField(blank=True, related_name='delivery_images_order', to='data_api.DeliveryImage'),
        ),
    ]
