# Generated by Django 3.2.8 on 2021-11-05 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0039_auto_20211103_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='mile_in',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
