# Generated by Django 3.2.8 on 2021-11-08 05:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data_api', '0041_auto_20211108_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrier',
            name='driver',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('trip_manager', 'TripManager'), ('sale_person', 'SalePerson'), ('back_officer', 'BackOfficer'), ('order_manager', 'OrderManager'), ('service_admin', 'ServiceAdmin')], max_length=20),
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_created_user', to=settings.AUTH_USER_MODEL)),
                ('updated_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_updated_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
