# Generated by Django 3.2.8 on 2021-11-08 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0042_auto_20211108_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrier',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_api.driver'),
        ),
        migrations.AddField(
            model_name='trip',
            name='carrier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_carrier', to='data_api.carrier'),
        ),
    ]
