# Generated by Django 3.2.8 on 2021-11-08 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0043_auto_20211108_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrier',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_api.userprofile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('trip_manager', 'TripManager'), ('sale_person', 'SalePerson'), ('back_officer', 'BackOfficer'), ('order_manager', 'OrderManager'), ('service_admin', 'ServiceAdmin'), ('driver', 'driver')], max_length=20),
        ),
    ]
