# Generated by Django 3.2.8 on 2022-02-11 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0044_auto_20211108_1503'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Driver',
        ),
    ]
