# Generated by Django 3.2.8 on 2022-02-11 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0046_auto_20220211_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('driver', 'driver'), ('admin', 'Admin'), ('judge', 'Judge'), ('teacher', 'Teacher'), ('student', 'Student')], max_length=20),
        ),
    ]
