# Generated by Django 3.2.8 on 2022-02-12 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0051_auto_20220212_1336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='year_level',
            new_name='class_level',
        ),
    ]
