# Generated by Django 3.2.8 on 2022-02-20 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data_api', '0053_auto_20220213_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='structurepreferredcourseenroll',
            name='lecturer',
        ),
        migrations.RemoveField(
            model_name='structurepreferredcourseenroll',
            name='section',
        ),
        migrations.RemoveField(
            model_name='transferringequivalentcourse',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='transferringequivalentcourse',
            name='advisor_name',
        ),
        migrations.RemoveField(
            model_name='transferringequivalentcourse',
            name='dean_faculty',
        ),
        migrations.RemoveField(
            model_name='transferringequivalentcourse',
            name='head_department_name',
        ),
        migrations.RemoveField(
            model_name='transferringequivalentcourse',
            name='head_educational_name',
        ),
        migrations.RemoveField(
            model_name='transferringequivalentcourse',
            name='semester',
        ),
        migrations.AddField(
            model_name='equivalentcourse',
            name='semester',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='structurepreferredcourseenroll',
            name='course',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='structurepreferredcourseenroll',
            name='course_year',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='structurepreferredcourseenroll',
            name='credit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='structurepreferredcourseenroll',
            name='credit_type',
            field=models.CharField(choices=[('ท', 'ท'), ('ป', 'ป'), ('ร', 'ร')], default='ท', max_length=20),
        ),
        migrations.AddField(
            model_name='structurepreferredcourseenroll',
            name='description_file',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='structurepreferredcourseenroll',
            name='subject',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='studentcoursestructure',
            name='course',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='studentcoursestructure',
            name='course_year',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='studentcoursestructure',
            name='credit_type',
            field=models.CharField(choices=[('ท', 'ท'), ('ป', 'ป'), ('ร', 'ร')], default='ท', max_length=20),
        ),
        migrations.AddField(
            model_name='studentcoursestructure',
            name='subject',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='transferringequivalentcourse',
            name='advisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advisor_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transferringequivalentcourse',
            name='advisor_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transferringequivalentcourse',
            name='dean',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dean_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transferringequivalentcourse',
            name='dean_approve',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transferringequivalentcourse',
            name='dean_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transferringequivalentcourse',
            name='dean_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transferringequivalentcourse',
            name='deputy_dean_a_r',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deputy_dean_a_r_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transferringequivalentcourse',
            name='deputy_dean_a_r_approve',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transferringequivalentcourse',
            name='deputy_dean_a_r_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transferringequivalentcourse',
            name='deputy_dean_a_r_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transferringequivalentcourse',
            name='equivalent_type',
            field=models.CharField(choices=[('ขอเทียบโอนรายวิชา', 'ขอเทียบโอนรายวิชา'), ('ขอเทียบเพื่อนเรียนแทน', 'ขอเทียบเพื่อนเรียนแทน')], default='ขอเทียบโอนรายวิชา', max_length=50),
        ),
        migrations.AddField(
            model_name='transferringequivalentcourse',
            name='head_academic_p_r',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='head_academic_p_r_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transferringequivalentcourse',
            name='head_academic_p_r_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transferringequivalentcourse',
            name='head_academic_p_r_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transferringequivalentcourse',
            name='head_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='head_department_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transferringequivalentcourse',
            name='head_department_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transferringequivalentcourse',
            name='head_educational',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='head_educational_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transferringequivalentcourse',
            name='head_educational_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transferringequivalentcourse',
            name='is_approve_committee5',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transferringequivalentcourse',
            name='is_approve_committee6',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transferringequivalentcourse',
            name='name_committee5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='committee5_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transferringequivalentcourse',
            name='name_committee6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='committee6_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transferringequivalentcourse',
            name='number_of_credit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transferringequivalentcourse',
            name='number_of_equivalent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transferringequivalentcourse',
            name='registrar_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrar_officer_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transferringequivalentcourse',
            name='registrar_officer_approve',
            field=models.CharField(choices=[('รอตรวจสอบ', 'รอตรวจสอบ'), ('ดำเนินการเรียบร้อย', 'ดำเนินการเรียบร้อย'), ('อื่นๆ', 'อื่นๆ')], default='รอตรวจสอบ', max_length=50),
        ),
        migrations.AddField(
            model_name='transferringequivalentcourse',
            name='registrar_officer_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transferringequivalentcourse',
            name='registrar_officer_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transferringequivalentcourse',
            name='studied_from',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='equivalentcourse',
            name='status',
            field=models.CharField(choices=[('รอตรวจสอบ', 'รอตรวจสอบ'), ('ได้', 'ได้'), ('ไม่ได้', 'ไม่ได้')], default='รอตรวจสอบ', max_length=50),
        ),
        migrations.AlterField(
            model_name='transferringequivalentcourse',
            name='name_committee1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='committee1_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transferringequivalentcourse',
            name='name_committee2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='committee2_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transferringequivalentcourse',
            name='name_committee3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='committee3_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transferringequivalentcourse',
            name='name_committee4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='committee4_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='level_of_study',
            field=models.CharField(blank=True, choices=[('ปวช', 'ระดับ ปวช.'), ('ปวส', 'ระดับ ปวส.'), ('ปตรี', 'ระดับปริญญาตรี')], max_length=50, null=True),
        ),
    ]
