# Generated by Django 3.2.8 on 2022-02-22 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0055_userprofile_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferringequivalentcourse',
            name='advisor_approve',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='transferringequivalentcourse',
            name='dean_approve',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='transferringequivalentcourse',
            name='deputy_dean_a_r_approve',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='transferringequivalentcourse',
            name='head_department_approve',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='transferringequivalentcourse',
            name='head_educational_approve',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='transferringequivalentcourse',
            name='is_approve_committee1',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='transferringequivalentcourse',
            name='is_approve_committee2',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='transferringequivalentcourse',
            name='is_approve_committee3',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='transferringequivalentcourse',
            name='is_approve_committee4',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='transferringequivalentcourse',
            name='is_approve_committee5',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='transferringequivalentcourse',
            name='is_approve_committee6',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
