# Generated by Django 3.2.8 on 2022-02-22 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0056_auto_20220222_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferringequivalentcourse',
            name='number_of_credit',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='transferringequivalentcourse',
            name='number_of_equivalent',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
