# Generated by Django 3.2.8 on 2022-02-22 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0057_auto_20220222_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferringequivalentcourse',
            name='registrar_officer_approve',
            field=models.CharField(choices=[('รอตรวจสอบ', 'รอตรวจสอบ'), ('ดำเนินการเรียบร้อย', 'ดำเนินการเรียบร้อย'), ('อื่นๆ', 'อื่นๆ')], default='รอตรวจสอบ', max_length=50, null=True),
        ),
    ]
