# Generated by Django 3.2.8 on 2022-02-24 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0059_auto_20220223_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='structurepreferredcourseenroll',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='structurepreferredcourseenroll',
            name='school',
        ),
    ]
