# Generated by Django 3.2.8 on 2022-08-14 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0060_auto_20220224_1014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equivalentcourse',
            name='student_course',
        ),
        migrations.AddField(
            model_name='equivalentcourse',
            name='student_course',
            field=models.ManyToManyField(blank=True, related_name='student_course_transferring_equivalent', to='data_api.StudentCourseStructure'),
        ),
    ]
